Fix File Q&A build error due to removed way of assigning options to the Formidable instance (#372)
* Pass maxFileSize attribute when instantiating IncomingForm()

Assigning a value through `form.maxFileSize` directly no longer works and will result in `Type error: Property 'maxFileSize' does not exist on type 'IncomingForm'.`

* Refactor Formidable instantiation acdg. to example shown in docs

Example usage acdg. to docs: https://github.com/node-formidable/formidable/blob/e5e25d2fd9a018c14d7f0014f0a9b8493892b68b/README.md#formidable--incomingform